spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/quest-platform?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:16379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
